version: "3.9"

services:
    cli:
        build:
            args:
                user: user
                uid: 1000
            context: .
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - postgres
        networks:
            - dev_network

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./:/var/www:ro # ro: read only
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - cli
        ports:
            - "8000:80"
        networks:
            - dev_network

    postgres:
        image: postgres:15.3
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
        networks:
            - dev_network
        volumes:
            - postgres-database:/var/lib/postgresql/data

    redis:
        image: redis:5.0.7-alpine
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        networks:
            - dev_network
        volumes:
            - "redis-database:/data"

    mailhog:
        image: "mailhog/mailhog:latest"
        ports:
            - "${FORWARD_MAILHOG_PORT:-1025}:1025"
            - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
        networks:
            - dev_network

networks:
    dev_network:
        driver: bridge

volumes:
    postgres-database:
        driver: local
    redis-database:
        driver: local
